### ISSUE TITLE
Frequently opening releases page

### ISSUE THREAD

**Issue by blackattireman** [Lich-Corals/linux-file-converter-addon#33]
hey i installed that extention to my Nautilus in Ubuntu back far ago but now it started to open this link  https://github.com/Lich-Corals/linux-file-converter-addon/releases with updates   of your extention. How can i turn that thing off? I am no expert in linux and it's super complicated but annoying. Thx for the read

**Comment by Lich-Corals** [comment]
Thanks for the report.
You can disable showPatchNotes in your config file.
See the head of [this page](https://github.com/Lich-Corals/linux-file-converter-addon/blob/main/markdown%2Fconfiguration.md) to see how to edit the file.
More detailed instructions for the specific setting are [here](https://github.com/Lich-Corals/linux-file-converter-addon/blob/main/markdown%2Fconfiguration.md#33-other-options).

You can also try to run Nautilus in the terminal to see, if it spits any errors at startup. It could also explain the problem, if the popup appears at every start of Nautilus.

I hope this reply is helpful. Please close the issue if it is solved; if it's not, you can just continue the conversation here.

**Comment by blackattireman** [comment]
hello thx for the responce, i thought i was working on github and not on private emails but ok. i have this problem when i run first instructions : nohup: failed to open 'nohup.out': Permission denied nohup: failed to open '/home/daniel/nohup.out': Permission denied what does it mean? how can i just delete that extention? i need to buy mac as soon as possible, this stuff is too much for me hehe On Mar 26, 2024, at 10:34 AM, Linus T. ***@***.***> wrote: Thanks for the report. You can disable showPatchNotes in your config file. See the head of this page to see how to edit the file. More detailed instructions for the specific setting are here . You can also try to run Nautilus in the terminal to see, if it spits any errors at startup. It could also explain the problem, if the popup appears at every start of Nautilus. I hope this reply is helpful. Please close the issue if it is solved; if it's not, you can just continue the conversation here. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by Lich-Corals** [comment]
You can remove the 'nohup', it just tells the computer to not run the app in the terminal, so you don't have to leave it open for this Nautilus session.
You can also just use your normal starter you normally use, the important command is the one with the '-q' in it.
The error just tells you, that you don't have writing permission in the dictionary where you ran the command. But as long as you're able to run Nautilus normally, it shouldn't be a problem.

Is your original issue solved?

**Comment by blackattireman** [comment]
i dont know maaan, what exactly should i do? what is nohup? i am not into that stuff at all... why it started to act this way, why i need to configure smth now? i dont even know where i installed it, it's too complicated, i just ran 2 commands in instraucion as it said when i was installing it i dont know when and now it needs my attention all the time like - oh look how we did this update! i dont want to see it, how can i delete it? linux sometimes is really complicated.... On Mar 26, 2024, at 6:46 PM, Linus T. ***@***.***> wrote: You can remove the 'nohup', it just tells the computer to not run the app in the terminal, so you don't have to leave it open for this Nautilus session. You can also just use your normal starter you normally use, the important command is the one with the '-q' in it. The error just tells you, that you don't have writing permission in the dictionary where you ran the command. But as long as you're able to run Nautilus normally, it shouldn't be a problem. Is your original issue solved? — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by Lich-Corals** [comment]
You need to configure it, because you installed the program in a location, where it doesn't have permission to update itself.
To solve your problem, please run these commands in your terminal:
```bash
sudo mv /usr/share/nautilus-python/extensions/nautilus-fileconverter.py ~/.local/share/nautilus-python/extensions/nautilus-fileconverter.py
```
```bash
nautilus -q
```
These commands will move the script to a place where it is able to update itself and close nautilus.
If you ran these commands, please start nautilus the normal way you always do it. It will probably show you the website one last time.

I hope this solution will solve your problem. Please close the issue if it did, otherwise, feel free to continue this conservation.

**Comment by blackattireman** [comment]
i ran 2 commands, on last one i got: ***@***.***:~$ nautilus -q GSConnect: No translation file found for domain WARNING(Nautilus-file-converter): "pyheif" not found, if you want to convert from heif format, install the package using "pip install pyheif". See the readme on GitHub for more information. WARNING(Nautilus-file-converter): "jxlpy" not found, if you want to convert from- or to jxl format, install the package using "pip install jxlpy". See the readme on GitHub for more information. Updating... nohup: failed to open 'nohup.out': Permission denied nohup: failed to open '/home/daniel/nohup.out': Permission denied kdeconnect-nautilus: [Errno 2] No translation file found for domain: 'kdeconnect-nautilus-extension' i hope it will fix itself but i dont unerstand the errors On Mar 28, 2024, at 7:01 PM, Linus T. ***@***.***> wrote: You need to configure it, because you installed the program in a location, where it doesn't have permission to update itself. To solve your problem, please run these commands in your terminal: sudo mv /usr/share/nautilus-python/extensions/nautilus-fileconverter.py ~ /.local/share/nautilus-python/extensions/nautilus-fileconverter.py nautilus -q These commands will move the script to a place where it is able to update itself and close nautilus. If you ran these commands, please start nautilus the normal way you always do it. It will probably show you the website one last time. I hope this solution will solve your problem. Please close the issue if it did, otherwise, feel free to continue this conservation. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>
