### ISSUE TITLE
Port the project to other file managers (Dolphin File Manager)

### ISSUE THREAD

**Issue by cfgnunes** [Lich-Corals/linux-file-converter-addon#38]
Hi @Lich-Corals ! Thanks for the project!

I have a similar project in:
https://github.com/cfgnunes/nautilus-scripts

I'm considering migrating it to Python (like yours), but before I proceed, I'm curious if there's a possibility of adapting your project to other file managers, such as Dolphin.

Could you please provide some insights or suggestions on this matter?

**Comment by Lich-Corals** [comment]
Sure, it should easily be possible to port it to another file manager. 
When I ported the script for Nemo, I added the functionality to just run the script with file paths as arguments. It shows a pop-up which prompts to select a new format and just writes the new image at the same location.

But it would need some more changes to work with Dolphin.
Currently, it's generating a dynamic (to just allow the right file types, depending on optional dependencies) .nemo_action file, which is just a context-menu add-on for Nemo, to its dictionary. If Dolphin also has the option to add a custom action to its context menu using a simple file with all the data about it, I don't see, why it shouldn't be possible.

It also shouldn't be too hard to rebuild the `FileConverterMenuProvider()` class (currently starting at line 403) if Dolphin also provides such a thing. This class is basically just telling Nautilus how to build the submenus, and which items should run which function. It is the only function, which is Nautilus-specific, the remaining script is relatively easy to use from other code.

I'm also planning to port this project for other widely used file managers, but I didn't read any more docs so far, so I don't know much about the possibilities in other file managers.

I hope this is helpful for you; if you have any further questions about the project or parts of the script, feel free to contact me.
