### ISSUE TITLE
Doesn't work in Arch with Gnome 46

### ISSUE THREAD

**Issue by borish127** [Lich-Corals/linux-file-converter-addon#41]
The installation is completed but the option convert to... doesn't appear in the menu

Arch Linux, Kernel 6.10
Gnome 46.4

All dependences installed

**Comment by Lich-Corals** [comment]
Thanks for the information.
I'll try to take care of this problem as soon as possible, but it might take some time, for I have quite a lot to do at the time.

**Comment by borish127** [comment]
Ok, no problem.
Anither think I forgot to say is that I have to install system wide because if install for especific user nautilus directly doesn't open.
Thanks, and don't worry, take your time.

**Comment by borish127** [comment]
![Screenshot from 2024-08-20 10-09-36](https://github.com/user-attachments/assets/a27e5900-e8f2-4df1-852e-78d1a42a0045)
First screenshot is when "nautilus -q"
![Screenshot from 2024-08-20 10-11-13](https://github.com/user-attachments/assets/f7829acb-cf85-47a4-809d-61f9c72cd14c)
Second screenshot when I try to launch nautilus again

I have installed nautilus-admin and nautilus_open_any_terminal in system wide and nautilus-gsconnect for my specific user

**Comment by borish127** [comment]
I moved nautilus-gsconnect to system-wide and tried installing file-converter as system-wide too.
![Screenshot from 2024-08-20 10-24-59](https://github.com/user-attachments/assets/cfeb9e21-fc0e-4325-9bdf-be6b91bb15c4)
Can it be a problem with permisions?
![Screenshot from 2024-08-20 10-25-42](https://github.com/user-attachments/assets/30adb388-cdf0-49f0-82a7-a3d8a7558212)

**Comment by borish127** [comment]
Solved!! The problem was the permisions to read and write in the folder extensions.
I granted with chmod and worked.
